#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c danilom<tab>/bo<tab>
#
# ...to quickly jump into ~/Workspace/github.com/danilomartinelli/boom.

if [[ -n $1 && -d $PROJECTS/$1 ]]; then
  cd "$PROJECTS/$1"
elif [[ -z $1 ]]; then
  cd "$PROJECTS"
else
  echo "c: no such project: $1" >&2
  return 1
fi
