#!/bin/sh

set -e

# shellcheck disable=SC1091
. "$(CDPATH='' cd -P -- "$(dirname -- "$0")/../_scripts" && pwd)/installer-preamble.sh"

installer_require_darwin
installer_banner "setting up OpenCode configuration"

CONFIG_DIR=$(installer_config_dir opencode)
CATALOG="${DOTFILES_OPENCODE_CATALOG:-$TOPIC_DIR/_managed-entries.tsv}"

if [ ! -f "$CATALOG" ]; then
  installer_fail "OpenCode entry catalog not found: $CATALOG"
fi

mkdir -p "$CONFIG_DIR"

installer_require_command opencode

installer_require_command ocx

ocx init --global
ocx registry add https://registry.kdco.dev --name kdco --global

OCX_RECEIPT="$CONFIG_DIR/.ocx/receipt.jsonc"
if [ -f "$OCX_RECEIPT" ] && grep -Fq '::kdco/workspace@' "$OCX_RECEIPT"; then
  installer_note "OCX workspace already installed"
else
  ocx add kdco/workspace --global
fi

# Every managed target is regenerated by its tool, so the catalog's conflict
# policy is stated once here rather than repeated at each call site.
link_managed_target() {
  installer_link_config \
    --policy replace-generated \
    --label "$1" \
    "$2" "$3"
}

configure_managed_entry() {
  entry_name=$1
  entry_source="$TOPIC_DIR/$entry_name"
  entry_target="$CONFIG_DIR/$entry_name"

  if [ ! -e "$entry_source" ]; then
    installer_fail "OpenCode config source not found: $entry_source"
  fi

  # OCX owns installation and updates; dotfiles owns the editable result.
  # Runtime-only entries such as plugins, .ocx and package.json stay untouched.
  link_managed_target "OpenCode $entry_name" "$entry_source" "$entry_target"
}

configure_profile() {
  profile_name=$1
  clone_source=${2:-}
  profile_source="$TOPIC_DIR/profiles/$profile_name"
  profile_target="$CONFIG_DIR/profiles/$profile_name"

  if [ ! -d "$profile_source" ]; then
    installer_fail "OpenCode profile source not found: $profile_source"
  fi

  ocx profile remove "$profile_name" --global
  if [ -n "$clone_source" ]; then
    ocx profile add "$profile_name" --clone "$clone_source" --global
  else
    ocx profile add "$profile_name" --global
  fi

  # OCX creates a profile directory. Replace that generated directory with the
  # repository-owned profile so edits remain versioned in dotfiles.
  link_managed_target "OpenCode $profile_name profile" \
    "$profile_source" "$profile_target"
}

# Apply the catalog in file order, so a clone source is always materialized
# before the profiles that clone it. Reading on file descriptor 3 leaves stdin
# free, so an ocx call below can never consume the rows still to be applied.
while IFS="$(printf '\t')" read -r catalog_kind catalog_name catalog_clone <&3; do
  case "$catalog_kind" in
    '' | \#*) continue ;;
  esac

  if [ -z "$catalog_name" ] || [ -z "$catalog_clone" ]; then
    installer_fail "invalid OpenCode catalog row: $catalog_kind $catalog_name"
  fi

  case "$catalog_kind" in
    entry)
      configure_managed_entry "$catalog_name"
      ;;
    profile)
      if [ "$catalog_clone" = - ]; then
        configure_profile "$catalog_name"
      else
        configure_profile "$catalog_name" "$catalog_clone"
      fi
      ;;
    *)
      installer_fail "unknown OpenCode catalog kind: $catalog_kind"
      ;;
  esac
done 3<"$CATALOG"

installer_success "OpenCode configured"
