#!/bin/sh

set -e

# shellcheck disable=SC1091
. "$(CDPATH='' cd -P -- "$(dirname -- "$0")/../_scripts" && pwd)/installer-preamble.sh"

installer_require_darwin
installer_banner "setting up OpenCode configuration"

CONFIG_DIR=$(installer_config_dir opencode)
CATALOG="${DOTFILES_OPENCODE_CATALOG:-$TOPIC_DIR/_managed-entries.tsv}"

if [ ! -f "$CATALOG" ]; then
  installer_fail "OpenCode entry catalog not found: $CATALOG"
fi

installer_require_command opencode
installer_require_command ocx
installer_require_command bun

validate_catalog_row() {
  catalog_kind=$1
  catalog_name=$2
  catalog_clone=$3

  if [ -z "$catalog_name" ] || [ -z "$catalog_clone" ]; then
    installer_fail "invalid OpenCode catalog row: $catalog_kind $catalog_name"
  fi

  case "$catalog_kind" in
    entry)
      [ -e "$TOPIC_DIR/$catalog_name" ] \
        || installer_fail "OpenCode config source not found: $TOPIC_DIR/$catalog_name"
      ;;
    profile)
      [ -d "$TOPIC_DIR/profiles/$catalog_name" ] \
        || installer_fail "OpenCode profile source not found: $TOPIC_DIR/profiles/$catalog_name"
      ;;
    *)
      installer_fail "unknown OpenCode catalog kind: $catalog_kind"
      ;;
  esac
  return 0
}

# A missing source or failed dependency install must leave the active plugin
# configuration in place. Resolve these prerequisites before activation.
catalog_each_row "$CATALOG" validate_catalog_row

# Competing orchestration hooks must be resolved before activating this runtime.
for competing_plugin in workspace-plugin background-agents; do
  competing_path=$CONFIG_DIR/plugins/$competing_plugin.ts
  if [ -e "$competing_path" ] || [ -L "$competing_path" ]; then
    installer_fail "OpenCode plugin conflicts with orchestrator: $competing_path. Resolve it before installing."
  fi
done

bun install --frozen-lockfile --ignore-scripts --cwd "$TOPIC_DIR/orchestrator"

mkdir -p "$CONFIG_DIR"

ocx init --global
ocx registry add https://registry.kdco.dev --name kdco --global

OCX_RECEIPT="$CONFIG_DIR/.ocx/receipt.jsonc"
install_runtime_plugins() {
  set --
  for runtime_component in worktree notify; do
    if [ ! -f "$OCX_RECEIPT" ] \
      || ! grep -Fq "::kdco/$runtime_component@" "$OCX_RECEIPT"; then
      set -- "$@" "kdco/$runtime_component"
    fi
  done
  [ "$#" -gt 0 ] || return 0
  ocx add "$@" --global
}

install_runtime_plugins

# Every managed target is regenerated by its tool, so the catalog's conflict
# policy is stated once here rather than repeated at each call site.
link_managed_target() {
  installer_link_config \
    --policy replace-generated \
    --label "$1" \
    "$2" "$3"
}

configure_managed_entry() {
  entry_name=$1
  entry_source="$TOPIC_DIR/$entry_name"
  entry_target="$CONFIG_DIR/$entry_name"

  if [ ! -e "$entry_source" ]; then
    installer_fail "OpenCode config source not found: $entry_source"
  fi

  # The local orchestrator and configuration are versioned here; OCX owns the
  # remaining plugin files, receipt and package dependencies.
  link_managed_target "OpenCode $entry_name" "$entry_source" "$entry_target"
}

configure_profile() {
  profile_name=$1
  clone_source=${2:-}
  profile_source="$TOPIC_DIR/profiles/$profile_name"
  profile_target="$CONFIG_DIR/profiles/$profile_name"

  if [ ! -d "$profile_source" ]; then
    installer_fail "OpenCode profile source not found: $profile_source"
  fi

  if [ -e "$profile_target" ] || [ -L "$profile_target" ]; then
    ocx profile remove "$profile_name" --global
  fi
  if [ -n "$clone_source" ]; then
    ocx profile add "$profile_name" --clone "$clone_source" --global
  else
    ocx profile add "$profile_name" --global
  fi

  # OCX creates a profile directory. Replace that generated directory with the
  # repository-owned profile so edits remain versioned in dotfiles.
  link_managed_target "OpenCode $profile_name profile" \
    "$profile_source" "$profile_target"
}

# One catalog row, applied in file order so a clone source is always
# materialized before the profiles that clone it.
configure_catalog_row() {
  catalog_kind=$1
  catalog_name=$2
  catalog_clone=$3

  case "$catalog_kind" in
    entry)
      configure_managed_entry "$catalog_name"
      ;;
    profile)
      if [ "$catalog_clone" = - ]; then
        configure_profile "$catalog_name"
      else
        configure_profile "$catalog_name" "$catalog_clone"
      fi
      ;;
    *)
      installer_fail "unknown OpenCode catalog kind: $catalog_kind"
      ;;
  esac
  return 0
}

catalog_each_row "$CATALOG" configure_catalog_row

installer_success "OpenCode configured"
