#!/usr/bin/env bash
#
# First-run adapter for the canonical setup module.

set -e

BOOTSTRAP_PATH=${BASH_SOURCE[0]}
ADAPTER_ANCHOR=$BOOTSTRAP_PATH
# shellcheck disable=SC1091
. "$(CDPATH='' cd -P -- "$(dirname -- "$BOOTSTRAP_PATH")" && pwd)/adapter-checkout.sh"

exec "$DOTFILES_ROOT/_scripts/setup" bootstrap
